### ISSUE TITLE
crashed on page load

### ISSUE THREAD

**Issue by wanderer** [clehner/git-ssb-web#2]
> git-ssb-web@1.7.0 start /home/null/code/git-ssb-web
> node server.js

Listening on http://localhost:7718/
GET /
GET /styles.css
/home/null/code/git-ssb-web/about.js:89
      var c = msg.value.content
                       ^

TypeError: Cannot read property 'content' of undefined
    at /home/null/code/git-ssb-web/about.js:89:24
    at /home/null/code/git-ssb-web/node_modules/pull-stream/sinks/drain.js:24:37
    at PacketStreamSubstream.weird.read (/home/null/code/git-ssb-web/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/null/code/git-ssb-web/node_modules/packet-stream/index.js:192:12)
    at PacketStream.write (/home/null/code/git-ssb-web/node_modules/packet-stream/index.js:123:41)
    at /home/null/code/git-ssb-web/node_modules/muxrpc/pull-weird.js:56:15
    at /home/null/code/git-ssb-web/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/null/code/git-ssb-web/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/null/code/git-ssb-web/node_modules/packet-stream-codec/index.js:107:11)
    at drain (/home/null/code/git-ssb-web/node_modules/pull-reader/index.js:39:14)

**Comment by wanderer** [comment]
it crashes [here](https://github.com/clehner/git-ssb-web/blob/master/about.js#L89) So I `console.log(msg)` and got the following

```
{ source: '@uikkwUQU4dcd/ZrHU7JstnkTgncxQB2A8PDLHV9wDAs=.ed25519',
  rel: 'about',
  dest: '@uikkwUQU4dcd/ZrHU7JstnkTgncxQB2A8PDLHV9wDAs=.ed25519',
  key: '%oHr2koP/K0SnPHE7V9BYiHvn0Ou4rhGGf6gGv57Lp+E=.sha256',
  value:
   { previous: '%x5MDmJfdyCDUnvMupqA8CCxcCvoii1v0n9agvOuBbtc=.sha256',
     author: '@uikkwUQU4dcd/ZrHU7JstnkTgncxQB2A8PDLHV9wDAs=.ed25519',
     sequence: 199,
     timestamp: 1452637334893,
     hash: 'sha256',
     content:
      { type: 'about',
        about: '@uikkwUQU4dcd/ZrHU7JstnkTgncxQB2A8PDLHV9wDAs=.ed25519',
        image: [Object] },
     signature: 'YDNqiKoFyJoWwhLL+jxhCIOcjaKtuHKEz6B8EMZtLDx8SzQEWTshiSrzJuiSy4wApiV7/p3ud083AMdFbALMDw==.sig.ed25519' } }
{ source: '@uikkwUQU4dcd/ZrHU7JstnkTgncxQB2A8PDLHV9wDAs=.ed25519',
  rel: 'about',
  dest: '@uikkwUQU4dcd/ZrHU7JstnkTgncxQB2A8PDLHV9wDAs=.ed25519',
  key: '%ZvdT6dYsE+lHIHCqBYH0Pa2FW+0QjdZra/CVfhYrTSw=.sha256',
  value:
   { previous: '%3LHhzx+2cHHpn/30Ud9hCEP3n61VLIU1J7VDh+Zk11Y=.sha256',
     author: '@uikkwUQU4dcd/ZrHU7JstnkTgncxQB2A8PDLHV9wDAs=.ed25519',
     sequence: 889,
     timestamp: 1460695186713,
     hash: 'sha256',
     content:
      { type: 'about',
        about: '@uikkwUQU4dcd/ZrHU7JstnkTgncxQB2A8PDLHV9wDAs=.ed25519',
        image: [Object] },
     signature: 'NvFIuX2rWdXcvdpPOz/FwTfxfaMfs1YLG6p5qqy/d9Rz6MEM1CMDjjrhPmLN4125bzyBGgfLcQYtv00RrKbPBw==.sig.ed25519' } }
{ sync: true }
```

the last message `{ sync: true }` is causing the crash

**Comment by wanderer** [comment]
ok so its doing this is several places, not just in about.js 

```
/home/null/code/git-ssb-web/node_modules/ssb-pull-requests/node_modules/ssb-issues/index.js:12
  return msg.value.author == issue.author
                  ^

TypeError: Cannot read property 'author' of undefined
    at isUpdateValid (/home/null/code/git-ssb-web/node_modules/ssb-pull-requests/node_modules/ssb-issues/index.js:12:19)
    at onNewMsg (/home/null/code/git-ssb-web/node_modules/ssb-pull-requests/node_modules/ssb-issues/index.js:129:12)
    at /home/null/code/git-ssb-web/node_modules/pull-stream/sinks/drain.js:24:37
    at PacketStreamSubstream.weird.read (/home/null/code/git-ssb-web/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/null/code/git-ssb-web/node_modules/packet-stream/index.js:192:12)
    at PacketStream.write (/home/null/code/git-ssb-web/node_modules/packet-stream/index.js:123:41)
    at /home/null/code/git-ssb-web/node_modules/muxrpc/pull-weird.js:56:15
    at /home/null/code/git-ssb-web/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/null/code/git-ssb-web/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/null/code/git-ssb-web/node_modules/packet-stream-codec/index.js:107:11)
```

**Comment by clehner** [comment]
I've added a check for this to ssb-issues, published in v0.1.1.
For the first error, your git-ssb-web version is out of date. Can you pull an update from the remote on git-ssb and try again? (`git pull ssb://%q5d5Du+9WkaSdjc8aJPZm+jMrqgo0tmfR+RcX5ZZ6H4=.sha256 master`)

**Comment by wanderer** [comment]
@clehner ok im at commit d36c25d80e23ebfa5b2010d14d2613721e83f2ff 

now im getting

```
> git-ssb-web@1.15.0 start /home/null/code/git-ssb-web
> node server.js

Listening on http://localhost:7718/
/home/null/code/git-ssb-web/node_modules/ssb-pull-requests/node_modules/ssb-issues/index.js:12
  return msg.value.author == issue.author
                  ^

TypeError: Cannot read property 'author' of undefined
    at isUpdateValid (/home/null/code/git-ssb-web/node_modules/ssb-pull-requests/node_modules/ssb-issues/index.js:12:19)
    at onNewMsg (/home/null/code/git-ssb-web/node_modules/ssb-pull-requests/node_modules/ssb-issues/index.js:129:12)
    at /home/null/code/git-ssb-web/node_modules/pull-stream/sinks/drain.js:24:37
    at PacketStreamSubstream.weird.read (/home/null/code/git-ssb-web/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/null/code/git-ssb-web/node_modules/packet-stream/index.js:192:12)
    at PacketStream.write (/home/null/code/git-ssb-web/node_modules/packet-stream/index.js:123:41)
    at /home/null/code/git-ssb-web/node_modules/muxrpc/pull-weird.js:56:15
    at /home/null/code/git-ssb-web/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/null/code/git-ssb-web/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/null/code/git-ssb-web/node_modules/packet-stream-codec/index.js:107:11)

npm ERR! Linux 4.5.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! git-ssb-web@1.15.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-ssb-web@1.15.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-ssb-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs git-ssb-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls git-ssb-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/null/code/git-ssb-web/npm-debug.log
```

**Comment by wanderer** [comment]
maybe ssb-issues needs to be bumped in ssb-pull-requests?

**Comment by clehner** [comment]
Pushed a fix now in `0d3f9e454b13bbf362f40fa20967d27c107b587a` (1.15.1) to add checks for msg.value and update the ssb-pull-requests dependency. Try again?

**Comment by wanderer** [comment]
thanks @clehner works now!

**Comment by clehner** [comment]
Cool!
